// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float2> Input;
RWStructuredBuffer<float> Output;

#include "AltitudeGenerator.cginc"

[numthreads(256,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{	
	Output[id.x] = GetAltitudeAtLocation(Input[id.x]);
}
