#pragma kernel CSMain

#define GetCameraRelativePositionWS(var)
#define TransformWorldToHClip(var) float4(0, 0, 0, 0)

#include "AltitudeGenerator.cginc"
#include "GPULandscapeShaderLibrary.cginc"


[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 pos = getVertexWorldPosition(id.x);

	// Retrieve altitude at vertex position
	float realAltitude = GetAltitudeAtLocation(pos.xz);
	
	_Altitude[id.x] = pos + float3(0, realAltitude, 0);
}

