#pragma kernel CSMain

#define GetCameraRelativePositionWS(var)
#define TransformWorldToHClip(var) float4(0, 0, 0, 0)

int _Subdivision;

#include "AltitudeGenerator.cginc"
#include "GPULandscapeShaderLibrary.cginc"


[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	const float2 texturePos = float2(id.x, id.y * _Subdivision);	
	float realAltitude = 2000;// GetAltitudeAtLocation(texturePos * _Width + _Offset);
	_Altitude[texturePos] = realAltitude;
}

